# -*- coding: utf-8 -*-
"""ML Lab 1 - 190334K - Label 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TGeNbiB3kjSLhxf11g6NrdwbdIff_cwY

Define label name and feature names
"""

import pandas as pd
import numpy as np

LBL = "label_4" # Speaker age
LABELS = ['label_1','label_2', 'label_3', 'label_4']
FEATURES = [f'feature_{i}' for i in range(1, 257)]

"""Read training,validation and test data"""

from google.colab import drive
drive.mount('/content/drive')


train_df = pd.read_csv("/content/drive/MyDrive/ML_lab1/train.csv")
valid_df = pd.read_csv("/content/drive/MyDrive/ML_lab1/valid.csv")
test_df = pd.read_csv("/content/drive/MyDrive/ML_lab1/test.csv")

"""Initialize dictionaries to store data"""

train_x = {}
valid_x = {}
test_x = {}
train_y = {}
valid_y = {}
test_y = {}

"""Prepare and preprocess the data"""

from sklearn.preprocessing import RobustScaler


scaler = RobustScaler()
train_x[LBL] = pd.DataFrame(scaler.fit_transform(train_df.drop(LABELS, axis=1)), columns = FEATURES)
train_y[LBL] = train_df[LBL]
valid_x[LBL] = pd.DataFrame(scaler.transform(valid_df.drop(LABELS, axis=1)), columns = FEATURES)
valid_y[LBL] = valid_df[LBL]
test_x[LBL] = pd.DataFrame(scaler.transform(test_df.drop(LABELS, axis=1)), columns=FEATURES)

"""# For Label 4

Train KNeighbors classifier
"""

from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(train_x[LBL], train_y[LBL])

"""Evaluate performance of KNeighbors classifier on the validation dataset"""

from sklearn import metrics

y_predict_valid = classifier.predict(valid_x[LBL])

print("KNeighbors Classifier Evaluation on Validation Set:")
print("Accuracy:", metrics.accuracy_score(valid_y[LBL], y_predict_valid))
print("Precision:", metrics.precision_score(valid_y[LBL], y_predict_valid, average='weighted'))
print("Recall:", metrics.recall_score(valid_y[LBL], y_predict_valid, average='weighted'))

"""Predict lable 1 for test dataset  using KNeighbors classifier"""

y_predict_test_before = classifier.predict(test_x[LBL])

"""## Applying Feature Engineering techniques

### Using PCA
"""

from sklearn.decomposition import PCA

pca = PCA(n_components=0.85, svd_solver='full')
pca.fit(train_x[LBL])

train_x_trans = pd.DataFrame(pca.transform(train_x[LBL]))
valid_x_trans = pd.DataFrame(pca.transform(valid_x[LBL]))
test_x_trans = pd.DataFrame(pca.transform(test_x[LBL]))

print("Shape after feature reduction:", train_x_trans.shape)

"""Train the KNeighbors classifier on PCA-transformed features

"""

classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(train_x_trans, train_y[LBL])

""":Evaluate performance of KNeighbors classifier on PCA-transformed features using validation dataset"""

y_predict_valid_pca = classifier.predict(valid_x_trans)

print("KNeighbors Classifier Evaluation on PCA-transformed features (Validation Set):")
print("Accuracy:", metrics.accuracy_score(valid_y[LBL], y_predict_valid_pca))
print("Precision:", metrics.precision_score(valid_y[LBL], y_predict_valid_pca, average='weighted'))
print("Recall:", metrics.recall_score(valid_y[LBL], y_predict_valid_pca, average='weighted'))

"""Predict lable 1 for test dataset after feature reduction"""

y_predict_test_after = classifier.predict(valid_x_trans)

output_df = pd.DataFrame({
    'Predicted labels before feature engineering': y_predict_test_before,
    'Predicted labels after feature engineering': y_predict_test_after,
    'No of new features': test_x_trans.shape[1]
})


for i in range(test_x_trans.shape[1]):
    output_df[f'new_feature_{i+1}'] = test_x_trans.iloc[:, i]
# Create a list of new column names
new_columns = [f'new_feature_{i+1}' for i in range(test_x_trans.shape[1], 256)]

# Concatenate the new columns to the existing DataFrame
output_df = pd.concat([output_df, pd.DataFrame(columns=new_columns)], axis=1)

output_df.to_csv('/content/drive/MyDrive/Colab Notebooks/files/190334K_label_4.csv', index=False)